### ISSUE TITLE
Problem with DICT_FILE in StructureProcessor

### ISSUE THREAD

**Issue by k8si** [iesl/rpp#1]
In StructureProcess, method mkRDoc(), there seems to be something wrong with the way we're trying to access the file "getClass.getResource("/words.txt")" (which does exist in the resources folder). Here's the exception:

Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: file:/home/kate/AI2/rpp/target/rpp-0.1-SNAPSHOT.jar!/words.txt (No such file or directory)
	at org.rexo.util.EnglishDictionary.create(EnglishDictionary.scala:28)
	at org.rexo.util.EnglishDictionary$.createDefault(EnglishDictionary.scala:58)
	at edu.umass.cs.iesl.rpp.StructureProcessor$.mkRDoc(StructureProcessor.scala:98)
	at edu.umass.cs.iesl.rpp.StructureProcessor$.process(StructureProcessor.scala:64)
	at edu.umass.cs.iesl.rpp.Cli$$anonfun$main$1.apply(Cli.scala:67)
	at edu.umass.cs.iesl.rpp.Cli$$anonfun$main$1.apply(Cli.scala:67)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:110)
	at scala.collection.immutable.List.foldLeft(List.scala:83)
	at edu.umass.cs.iesl.rpp.Cli$.main(Cli.scala:67)
	at edu.umass.cs.iesl.rpp.Cli.main(Cli.scala)
Caused by: java.io.FileNotFoundException: file:/home/kate/AI2/rpp/target/rpp-0.1-SNAPSHOT.jar!/words.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at scala.io.Source$.fromFile(Source.scala:91)
	at scala.io.Source$.fromFile(Source.scala:76)
	at org.rexo.util.EnglishDictionary.create(EnglishDictionary.scala:22)

Does anyone know offhand why this is happening/how to fix?

**Comment by strubell** [comment]
I've seen this problem before, basically accessing the resources in that
way only works if you're not running from a jar

**Comment by nmonath** [comment]
I think I ran into this problem as well. I did something like [this](https://github.com/iesl/paper_coref/blob/develop/scripts/rpp/batchrun.sh) to work around it:

```
root=$1
lexicons=$2
citeCRF="file://$root/citationCRF.factorie"
headerCRF="$root/headerCRF.factorie"
dataFilesFile=$3
outputDir=$4

CP="$root/target/classes:$root/target/rpp-0.1-SNAPSHOT-jar-with-dependencies.jar"

mem="4G"

java -Xmx${mem} -cp $CP -Dcc.factorie.app.nlp.lexicon.Lexicon=$lexicons edu.umass.cs.iesl.rpp.BatchMain \
--reference-model-uri=$citeCRF \
--header-tagger-model=$headerCRF \
--data-files-file=$dataFilesFile \
--output-dir=$outputDir
```
